#import '../fragments/page-path.gql'
#import '../../modules/03-01-MultiColumnLayout/fragment.gql'
#import '../../modules/03-04-FullscreenMedia/fragment.gql'

query GetPage($slug: String, $locale: SiteLocale) {
  page(filter: { slug: { eq: $slug } }, locale: $locale) {
    updatedAt
    id
    slug
    seo: _seoMetaTags {
      attributes
      content
      tag
    }
    modules {
      ... on MulticolumnLayoutRecord {
        ...multiColumnLayout
      }
      ... on FullscreenMediumRecord {
        ...fullscreenMedia
      }
    }
  }
}

# Add additional locales if there are more than two languages
query GetAllPages($locale1: SiteLocale, $locale2: SiteLocale) {
  de: allPages(first: "100", locale: $locale1) {
    ...pagePath
  }
  en: allPages(first: "100", locale: $locale2) {
    ...pagePath
  }
}
